server:
  port: 8080

spring:
  application:
    name: backend-service
  profiles:
    active: default
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/laptopshop
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update



